name: Dynasty International
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49261
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Dynasty International Marketing: The Movement'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f5f5'
    - '#e12415'
    - '#000000'
    - '#bbbbbb'
    - '#545454'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
